# Generated by Django 4.0.4 on 2022-05-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_basket_item_user_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basket_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shoe_stock'),
        ),
        migrations.AlterField(
            model_name='user',
            name='basket',
            field=models.ManyToManyField(related_name='basket_items', to='users.basket_item'),
        ),
    ]
