# Generated by Django 4.0.4 on 2022-05-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0004_basket_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basket',
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('order_number', models.CharField(max_length=32)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shoe_image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
