# Generated by Django 4.0.4 on 2022-05-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0005_remove_user_basket_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='item',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.shoe_stock'),
            preserve_default=False,
        ),
    ]
