# Generated by Django 4.0.4 on 2022-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_item_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
