# Generated by Django 4.0.4 on 2022-05-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_order_item_date_placed_alter_order_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='00000000000', max_length=64),
            preserve_default=False,
        ),
    ]
