# Generated by Django 4.0.4 on 2022-05-30 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='date_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
