# Generated by Django 4.0.4 on 2022-05-27 12:54

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gender', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN')], max_length=6)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Casual'), (2, 'Sport')], max_length=3)),
                ('product_type', models.CharField(choices=[('Shoes', 'Shoes'), ('Laces', 'Laces')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='shoe_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=128)),
                ('hex_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='shoe_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('size', models.IntegerField()),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.shoe_color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='shoe_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/png/shoes')),
                ('is_primary', models.BooleanField(null=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
