# Generated by Django 4.0.4 on 2022-05-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='name',
        ),
    ]
