# Generated by Django 4.0.4 on 2022-05-17 14:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_shoe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Casual'), (2, 'Sport')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN')], default='', max_length=6),
            preserve_default=False,
        ),
    ]
